<!--<script type="text/javascript" src="{{ url_for(theme.js) }}/src/scrollspy.js?v={{ theme.version }}"></script>-->
<!--<script type="text/javascript" src="{{ url_for(theme.js) }}/src/post-details.js?v={{ theme.version }}"></script>-->
<script type="text/javascript" src="//cdn.jsdelivr.net/gh/Tinyuen/blogcdn@0.0.1/js/scrollspy.min.js"></script>
<script type="text/javascript" src="//cdn.jsdelivr.net/gh/Tinyuen/blogcdn@0.0.1/js/post-details.min.js"></script>

