{% if theme.save_scroll %}
<!--  <script type="text/javascript" src="{{ url_for(theme.js) }}/src/js.cookie.js?v={{ theme.version }}"></script>-->
<!--  <script type="text/javascript" src="{{ url_for(theme.js) }}/src/scroll-cookie.js?v={{ theme.version }}"></script>-->
<script type="text/javascript" src="//cdn.jsdelivr.net/gh/Tinyuen/blogcdn@0.0.1/js/js.cookie.min.js"></script>
<script type="text/javascript" src="//cdn.jsdelivr.net/gh/Tinyuen/blogcdn@0.0.1/js/scroll-cookie.min.js"></script>
{% endif %}
